name: Nick Prokesch
markdown: redcarpet
highligher: pygments
email: nick@prokes.ch
job_title: junior ruby developer
twitter: prokizzle
github_name: prokizzle
title: Nick Prokesch
gravatar: 068dacb310f3395cd781e2a7cc729c63
permalink: /blog/:title
baseurl: http://nick.prokes.ch
author:
  name: Nick Prokesch
  email: nick@prokes.ch
