name: Nick Prokesch
markdown: redcarpet
highligher: pygments
email: nick@prokes.ch
job_title: full stack developer
twitter: prokizzle
github_name: prokizzle
title: Nick Prokesch
gravatar: cd0808a234fef3b971422e6f4107e2c8
permalink: /blog/:title
# baseurl: http://nick.prokes.ch
author:
  name: Nick Prokesch
  email: nick@prokes.ch
